runtime: python312
entrypoint: gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app

env: flex

env_variables:
  # Application Settings
  APP_NAME: "DeepDive Tracking"
  APP_ENV: "production"
  DEBUG: "False"
  LOG_LEVEL: "INFO"

  # Database - Cloud SQL
  DATABASE_URL: "postgresql://deepdive_user:deepdive_password@35.189.186.161:5432/deepdive_db"

  # Redis Cache - Cloud Memorystore
  REDIS_URL: "redis://10.240.18.115:6379/0"
  REDIS_CACHE_TTL: "3600"

  # Celery - Cloud Tasks
  CELERY_BROKER_URL: "redis://10.240.18.115:6379/1"
  CELERY_RESULT_BACKEND: "redis://10.240.18.115:6379/2"

  # External APIs - OpenAI
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  OPENAI_MODEL: "gpt-4o"
  OPENAI_TEMPERATURE: "0.3"
  OPENAI_MAX_TOKENS: "1000"

  # Publishing Channels - Email (Gmail)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "${GMAIL_USER}"
  SMTP_PASSWORD: "${GMAIL_APP_PASSWORD}"
  SMTP_FROM_EMAIL: "${GMAIL_USER}"
  SMTP_FROM_NAME: "DeepDive Tracking"
  EMAIL_LIST: "${EMAIL_LIST}"

  # Publishing Channels - GitHub
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  GITHUB_REPO: "${GITHUB_REPO}"
  GITHUB_USERNAME: "${GITHUB_USERNAME}"
  GITHUB_LOCAL_PATH: "/tmp/github_repo"

  # Publishing Channels - WeChat Official Account
  WECHAT_API_URL: "https://api.weixin.qq.com"
  WECHAT_APP_ID: "${WECHAT_APP_ID}"
  WECHAT_APP_SECRET: "${WECHAT_APP_SECRET}"

  # Feature Flags
  ENABLE_AI_SCORING: "True"
  ENABLE_DUPLICATE_DETECTION: "True"
  ENABLE_AUTO_PUBLISHING: "False"
  ENABLE_ANALYTICS: "True"

beta_settings:
  cloud_sql_instances: "deepdive-engine:asia-east1:deepdive-db"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
